// <auto-generated />
using System;
using BodegaLuchito.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BodegaLuchito.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BodegaLuchitoDbContext))]
    [Migration("20261002045103_AgregarVentas")]
    partial class AgregarVentas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("BodegaLuchito.Domain.Abastecimiento.Entities.Abastecimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Abastecimiento", (string)null);
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Abastecimiento.Entities.DetalleAbastecimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AbastecimientoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("PrecioUnitario");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalLinea")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Subtotal");

                    b.HasKey("Id");

                    b.HasIndex("AbastecimientoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetalleAbastecimiento", (string)null);
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Autenticacion.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Caja.Entities.MovimientoCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AbastecimientoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SesionCajaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VentaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SesionCajaId");

                    b.ToTable("MovimientosCaja", (string)null);
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Caja.Entities.SesionCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DiferenciaEfectivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiferenciaPlin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiferenciaYape")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EfectivoEsperado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EfectivoReal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FondoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ObservacionCierre")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PlinEsperado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PlinReal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioAperturaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioCierreId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("YapeEsperado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("YapeReal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Sesionescaja", (string)null);
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Inventario.Entities.MovimientoInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AbastecimientoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StockAnterior")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("StockPosterior")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId", "FechaHora");

                    b.ToTable("MovimientosInventario", (string)null);
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Productos.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Productos.Entities.HistorialActividadProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId", "FechaHora");

                    b.ToTable("HistorialActividadProducto", (string)null);
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Productos.Entities.HistorialPrecioProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioAnterior")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioNuevo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId", "FechaHora");

                    b.ToTable("HistorialPreciosProducto", (string)null);
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Productos.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ControlaInventario")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadVenta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoBarras")
                        .IsUnique();

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Proveedores.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ruc")
                        .IsUnique();

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Ventas.Entities.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetallesVenta", (string)null);
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Ventas.Entities.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Anulado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IGV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotivoAnulacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UsuarioAnulacionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ventas", (string)null);
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Abastecimiento.Entities.Abastecimiento", b =>
                {
                    b.HasOne("BodegaLuchito.Domain.Proveedores.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Abastecimiento.Entities.DetalleAbastecimiento", b =>
                {
                    b.HasOne("BodegaLuchito.Domain.Abastecimiento.Entities.Abastecimiento", "Abastecimiento")
                        .WithMany("Detalles")
                        .HasForeignKey("AbastecimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BodegaLuchito.Domain.Productos.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Abastecimiento");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Caja.Entities.MovimientoCaja", b =>
                {
                    b.HasOne("BodegaLuchito.Domain.Caja.Entities.SesionCaja", "SesionCaja")
                        .WithMany("Movimientos")
                        .HasForeignKey("SesionCajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SesionCaja");
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Inventario.Entities.MovimientoInventario", b =>
                {
                    b.HasOne("BodegaLuchito.Domain.Productos.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Productos.Entities.HistorialActividadProducto", b =>
                {
                    b.HasOne("BodegaLuchito.Domain.Productos.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Productos.Entities.HistorialPrecioProducto", b =>
                {
                    b.HasOne("BodegaLuchito.Domain.Productos.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Productos.Entities.Producto", b =>
                {
                    b.HasOne("BodegaLuchito.Domain.Productos.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Ventas.Entities.DetalleVenta", b =>
                {
                    b.HasOne("BodegaLuchito.Domain.Productos.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BodegaLuchito.Domain.Ventas.Entities.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Ventas.Entities.Venta", b =>
                {
                    b.HasOne("BodegaLuchito.Domain.Autenticacion.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Abastecimiento.Entities.Abastecimiento", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Caja.Entities.SesionCaja", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("BodegaLuchito.Domain.Ventas.Entities.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
